######################################################################
# Automatically generated by qmake (2.01a) Tue May 15 19:00:50 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += joy.h MainFrame.h
FORMS += main.ui
SOURCES += joy.cpp main.cpp MainFrame.cpp
