######################################################################
# Automatically generated by qmake (2.01a) Tue May 22 19:11:55 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += socket.h
FORMS += main.ui
SOURCES += main.cpp socket.cpp
QT += network
