######################################################################
# Automatically generated by qmake (2.01a) Sun May 27 15:37:47 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += socket.h
FORMS += main.ui
SOURCES += main.cpp socket.cpp
QT += network
