######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 6 19:27:59 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += console.cpp
