######################################################################
# Automatically generated by qmake (2.01a) Tue May 15 19:35:37 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += glwidget.h joy.h window.h
SOURCES += glwidget.cpp joy.cpp main.cpp window.cpp
QT += opengl
