######################################################################
# Automatically generated by qmake (2.01a) Sun May 13 20:23:12 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += GLWidget.h
SOURCES += GLWidget.cpp main.cpp
QT += opengl
